name: Pin

on:
  schedule:
    - cron:  '0 */2 * * *'

jobs:
  pinit:
    runs-on: ubuntu-latest
    steps:
      - name: Download docs
        run: wget -e robots=off -r -np --page-requisites https://swarm-gateways.net/bzz:/docs.swarm.eth/ || true
      - name: Download book
        run: wget -e robots=off -r -np --page-requisites https://swarm-gateways.net/bzz:/latest.bookofswarm.eth/ || true
