name: Pin

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  pinit:
    runs-on: ubuntu-latest
    steps:
      - name: Download docs
        run: wget https://gateway.ethswarm.org/bzz/1up1up1up.eth/ || true      
        # run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/1up1up1up.eth/ || true
