name: Pin

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  pinit:
    runs-on: ubuntu-latest
    steps:
      - name: Download docs
        run: wget -t1 -T100 -e robots=off -r -np --page-requisites  http://35.180.30.92:1633/bzz/eba7925a4d82c33affaf95fbf3885096487ceb27d8c9f1601f73db4f8ec7624a/docs/
      - name: Download docs
        run: wget -t1 -T100 -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/eba7925a4d82c33affaf95fbf3885096487ceb27d8c9f1601f73db4f8ec7624a/ || true
      - name: Download frontpage
        run: wget -t1 -T100 -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/e5fd2fed9e051617b57d9a85e5fe57b349ad85302b38c26a9e5c168efe4b87d2/ || true
      - name: Download 1up1up1up.eth
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/1up1up1up.eth/ || true
      - name: Download swarm.eth
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/swarm.eth/ || true
      - name: Download swarm.eth/editable.html
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/swarm.eth/editable.html || true
      - name: Download swarm.eth/jobs-cloud-engineer.html
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/swarm.eth/jobs-cloud-engineer.html || true
      - name: Download swarm.eth/jobs-go-developer.html
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/swarm.eth/jobs-go-developer.html || true
      - name: Download swarm.eth/jobs-senior-go-developer.html
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/swarm.eth/jobs-senior-go-developer.html || true
      - name: Download front
        run: wget -t1 -T100 -e robots=off -r -np --page-requisites  http://35.180.30.92:1633/bzz/e5fd2fed9e051617b57d9a85e5fe57b349ad85302b38c26a9e5c168efe4b87d2/
      - name: Download docs.swarm.eth
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/docs.swarm.eth/ || true
      - name: Download docs.swarm.eth/docs/
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/docs.swarm.eth/docs/ || true
      - name: Download liberate.swarm.eth/docs/
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/liberate.swarm.eth/ || true
      - name: Download latest.bookofswarm.eth/
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/latest.bookofswarm.eth/ || true
      - name: Download ecosystem
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/e5fd2fed9e051617b57d9a85e5fe57b349ad85302b38c26a9e5c168efe4b87d2/ecosystem.html
      - name: Download editable
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/e5fd2fed9e051617b57d9a85e5fe57b349ad85302b38c26a9e5c168efe4b87d2/editable.html
      - name: Download index
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/e5fd2fed9e051617b57d9a85e5fe57b349ad85302b38c26a9e5c168efe4b87d2/index.html
      - name: Download jobs-cloud-engineer
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/e5fd2fed9e051617b57d9a85e5fe57b349ad85302b38c26a9e5c168efe4b87d2/jobs-cloud-engineer.html
      - name: Download docs.swarm.eth
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/e5fd2fed9e051617b57d9a85e5fe57b349ad85302b38c26a9e5c168efe4b87d2/jobs-go-developer.html
      - name: Download docs.swarm.eth
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/e5fd2fed9e051617b57d9a85e5fe57b349ad85302b38c26a9e5c168efe4b87d2/jobs-infrastructure-engineer.html
      - name: Download docs.swarm.eth
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/e5fd2fed9e051617b57d9a85e5fe57b349ad85302b38c26a9e5c168efe4b87d2/jobs-security-researcher.html
      - name: Download docs.swarm.eth
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/e5fd2fed9e051617b57d9a85e5fe57b349ad85302b38c26a9e5c168efe4b87d2/jobs-senior-go-developer.html
      - name: Download docs.swarm.eth
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/e5fd2fed9e051617b57d9a85e5fe57b349ad85302b38c26a9e5c168efe4b87d2/jobs-social-media.html
      - name: Download docs.swarm.eth
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/e5fd2fed9e051617b57d9a85e5fe57b349ad85302b38c26a9e5c168efe4b87d2/jobs-technical-writer.html
      - name: Download docs.swarm.eth
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/e5fd2fed9e051617b57d9a85e5fe57b349ad85302b38c26a9e5c168efe4b87d2/junior-team-assistant.html
      - name: Download docs.swarm.eth
        run: wget -e robots=off -r -np --page-requisites https://gateway.ethswarm.org/bzz/e5fd2fed9e051617b57d9a85e5fe57b349ad85302b38c26a9e5c168efe4b87d2/register.html
        
      
